### ISSUE TITLE
[Request] Get the UTC Offset, getUtcOffsetMinutes()

### ISSUE THREAD

**Issue by rondey** [benedictkhoo/nativescript-google-places-sdk#1]
Hello, thanks for this plugin. Can you add the UTC Offset from the result? Thanks.
In the meantime i'm trying to add the types in the result

**Comment by benedictkhoo** [comment]
Hi @rondey , sure thing. Glad to hear that you are finding this plugin useful!

**Comment by benedictkhoo** [comment]
Hi @rondey , apologies for the late response. I managed to regenerate the typings and now you can get the UTC offset from the results.
